import {
  BUSINESS_TYPE_DATA_LIST_COLUMN_MIN_WIDTH,
  CURRENCY_DATA_LIST_COLUMN_MIN_WIDTH,
  DATA_LIST_FIGMA_HEADER_HEIGHT,
} from '@/scenes/tasks/tasksDataListPageData';
import { BATCH_AMOUNT_COLUMN_MIN_WIDTH } from '@/scenes/tasks/signing/batch/batchDataListLayout';

export const PARALLEL_OUT_DETAIL_COLUMN_HEIGHT = 66;
export const PARALLEL_OUT_DETAIL_AMOUNT_COLUMN_MIN_WIDTH = BATCH_AMOUNT_COLUMN_MIN_WIDTH;
export const PARALLEL_OUT_DETAIL_TYPE_COLUMN_MIN_WIDTH = '104px';
export const PARALLEL_OUT_DETAIL_SENDER_COLUMN_MIN_WIDTH =
  BUSINESS_TYPE_DATA_LIST_COLUMN_MIN_WIDTH;
export const PARALLEL_OUT_DETAIL_RECEIVER_COLUMN_MIN_WIDTH =
  CURRENCY_DATA_LIST_COLUMN_MIN_WIDTH;

export const PARALLEL_OUT_DETAIL_HEADER_HEIGHT = DATA_LIST_FIGMA_HEADER_HEIGHT;
